// <auto-generated />
namespace OnTap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class updateSV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSV));
        
        string IMigrationMetadata.Id
        {
            get { return "201911291324051_updateSV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
