// <auto-generated />
namespace OnTap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class createDanhBa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createDanhBa));
        
        string IMigrationMetadata.Id
        {
            get { return "201911230903096_createDanhBa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
